IF Object_ID ('GCE.global_co2_data','U') is not null
Drop table GCE.global_co2_data;
GO

CREATE TABLE GCE.global_co2_data
(
    country NVARCHAR(100) NULL,
    year INT NULL,
    iso_code NVARCHAR(10) NULL,
    population BIGINT NULL,
    gdp DECIMAL(18,2) NULL,
    cement_co2 DECIMAL(18,2) NULL,
    cement_co2_per_capita DECIMAL(18,2) NULL,
    co2 DECIMAL(18,2) NULL,
    co2_growth_abs DECIMAL(18,2) NULL,
    co2_growth_prct DECIMAL(18,2) NULL,
    co2_including_luc DECIMAL(18,2) NULL,
    co2_including_luc_growth_abs DECIMAL(18,2) NULL,
    co2_including_luc_growth_prct DECIMAL(18,2) NULL,
    co2_including_luc_per_capita DECIMAL(18,2) NULL,
    co2_including_luc_per_gdp DECIMAL(18,2) NULL,
    co2_including_luc_per_unit_energy DECIMAL(18,2) NULL,
    co2_per_capita DECIMAL(18,2) NULL,
    co2_per_gdp DECIMAL(18,2) NULL,
    co2_per_unit_energy DECIMAL(18,2) NULL,
    coal_co2 DECIMAL(18,2) NULL,
    coal_co2_per_capita DECIMAL(18,2) NULL,
    consumption_co2 DECIMAL(18,2) NULL,
    consumption_co2_per_capita DECIMAL(18,2) NULL,
    consumption_co2_per_gdp DECIMAL(18,2) NULL,
    cumulative_cement_co2 DECIMAL(18,2) NULL,
    cumulative_co2 DECIMAL(18,2) NULL,
    cumulative_co2_including_luc DECIMAL(18,2) NULL,
    cumulative_coal_co2 DECIMAL(18,2) NULL,
    cumulative_flaring_co2 DECIMAL(18,2) NULL,
    cumulative_gas_co2 DECIMAL(18,2) NULL,
    cumulative_luc_co2 DECIMAL(18,2) NULL,
    cumulative_oil_co2 DECIMAL(18,2) NULL,
    cumulative_other_co2 DECIMAL(18,2) NULL,
    energy_per_capita DECIMAL(18,2) NULL,
    energy_per_gdp DECIMAL(18,2) NULL,
    flaring_co2 DECIMAL(18,2) NULL,
    flaring_co2_per_capita DECIMAL(18,2) NULL,
    gas_co2 DECIMAL(18,2) NULL,
    gas_co2_per_capita DECIMAL(18,2) NULL,
    ghg_excluding_lucf_per_capita DECIMAL(18,2) NULL,
    ghg_per_capita DECIMAL(18,2) NULL,
    land_use_change_co2 DECIMAL(18,2) NULL,
    land_use_change_co2_per_capita DECIMAL(18,2) NULL,
    methane DECIMAL(18,2) NULL,
    methane_per_capita DECIMAL(18,2) NULL,
    nitrous_oxide DECIMAL(18,2) NULL,
    nitrous_oxide_per_capita DECIMAL(18,2) NULL,
    oil_co2 DECIMAL(18,2) NULL,
    oil_co2_per_capita DECIMAL(18,2) NULL,
    other_co2_per_capita DECIMAL(18,2) NULL,
    other_industry_co2 DECIMAL(18,2) NULL,
    primary_energy_consumption DECIMAL(18,2) NULL,
    share_global_cement_co2 DECIMAL(18,2) NULL,
    share_global_co2 DECIMAL(18,2) NULL,
    share_global_co2_including_luc DECIMAL(18,2) NULL,
    share_global_coal_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_cement_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_co2_including_luc DECIMAL(18,2) NULL,
    share_global_cumulative_coal_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_flaring_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_gas_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_luc_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_oil_co2 DECIMAL(18,2) NULL,
    share_global_cumulative_other_co2 DECIMAL(18,2) NULL,
    share_global_flaring_co2 DECIMAL(18,2) NULL,
    share_global_gas_co2 DECIMAL(18,2) NULL,
    share_global_luc_co2 DECIMAL(18,2) NULL,
    share_global_oil_co2 DECIMAL(18,2) NULL,
    share_global_other_co2 DECIMAL(18,2) NULL,
    share_of_temperature_change_from_ghg DECIMAL(18,2) NULL,
    temperature_change_from_ch4 DECIMAL(18,2) NULL,
    temperature_change_from_co2 DECIMAL(18,2) NULL,
    temperature_change_from_ghg DECIMAL(18,2) NULL,
    temperature_change_from_n2o DECIMAL(18,2) NULL,
    total_ghg DECIMAL(18,2) NULL,
    total_ghg_excluding_lucf DECIMAL(18,2) NULL,
    trade_co2 DECIMAL(18,2) NULL,
    trade_co2_share DECIMAL(18,2) NULL
);

Truncate table GCE.global_co2_data
Bulk Insert GCE.global_co2_data
From 'C:\Users\Phuc\SQL-Projects\sql-global-co2-emissions-project\datasets\global_co2_data.csv'
With (
	Firstrow = 2,
	Fieldterminator = ',',
    Rowterminator = '0x0a',
	tablock
	)
--Use table GCE.global_co2_data--
Select * From GCE.global_co2_data